#!/usr/bin/env bash

while [ ! "${WIFI_HOSTNAME}" ]
do
    echo -n "Hostname of ESP32: "
    read WIFI_HOSTNAME
done

while [ ! "${WIFI_SSID}" ]
do
    echo -n "WiFi SSID: "
    read WIFI_SSID
done

while [ ! "${WIFI_PASSWORD}" ]
do
    echo -n "WiFi Password: "
    read WIFI_PASSWORD
done

while [ ! "${KODI_HOSTNAME}" ]
do
    echo -n "Kodi hostname or IP address: "
    read KODI_HOSTNAME
done

echo "#define WIFI_HOSTNAME \"${WIFI_HOSTNAME}\"
#define WIFI_SSID \"${WIFI_SSID}\"
#define WIFI_PASSWORD \"${WIFI_PASSWORD}\"
#define JSONRPC_URL \"http://${KODI_HOSTNAME}:8080/jsonrpc\"" > Secrets.h

# vim: syntax=sh expandtab tabstop=4 shiftwidth=4 softtabstop=4:
